//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst_18440038
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogrenci
    {
        public int ID { get; set; }
        public string isim { get; set; }
        public string dersno { get; set; }
        public string sifre { get; set; }
        public int adminID { get; set; }
    
        public virtual admin1 admin { get; set; }
    }
}
