//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst_18440038
{
    using System;
    using System.Collections.Generic;
    
    public partial class sorular
    {
        public int ID { get; set; }
        public string baslik { get; set; }
        public string cvpa { get; set; }
        public string cvpb { get; set; }
        public string cvpc { get; set; }
        public string dogrucvp { get; set; }
        public int adminID { get; set; }
        public int sinavID { get; set; }
    
        public virtual List<admin1> admin { get; set; }
        public virtual List<sinav> sinav { get; set; }
    }
}
