//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst_18440038
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sinavDBModelContainer : DbContext
    {
        public sinavDBModelContainer()
            : base("name=sinavDBModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin1> admin1Set { get; set; }
        public virtual DbSet<ogrenci> ogrenciSet { get; set; }
        public virtual DbSet<sorular> sorularSet { get; set; }
        public virtual DbSet<sinav> sinavSet { get; set; }
    }
}
